title: OpenSocial Docs
description: Docs
theme: just-the-docs

url: https://kyranstar.github.io/social-docs.github.io/

aux_links:
  OpenSocial: https://github.com/just-the-docs/just-the-docs-template
